development:
 access_key_id: "#{ENV['AWS_ACCESS_KEY_ID']}"
 secret_access_key: "#{ENV['AWS_SECRET_ACCESS_KEY']}"
 bucket: party-tv-staging

staging:
 access_key_id: "#{ENV['AWS_ACCESS_KEY_ID']}"
 secret_access_key: "#{ENV['AWS_SECRET_ACCESS_KEY']}"
 bucket: party-tv-staging

production:
 access_key_id: "#{ENV['AWS_ACCESS_KEY_ID']}"
 secret_access_key: "#{ENV['AWS_SECRET_ACCESS_KEY']}"
 bucket: party-tv
